### ISSUE TITLE
Version 2.6.3 not found error

### ISSUE THREAD

**Issue by adbeelitamar** [actions/setup-ruby#56] opened 2020-01-24 20:23 UTC
Is ruby version 2.6.3 not supported anymore by this action ? I'm specifying exact version as follows:

```
- name: Set up Ruby 2.6
  uses: actions/setup-ruby@v1
  with:
    ruby-version: 2.6.3
```
And, I'm getting the following error:
```
Run actions/setup-ruby@v1
  with:
    ruby-version: 2.6.3
##[error]Version 2.6.3 not found
##[error]Node run failed with exit code 1
```

If I do `2.6` or `2.6.x` it gets version 2.6.5. Is there any other way to force the use of the version i want?

**Comment by MSP-Greg** [comment] 2020-01-24 22:18
With a recent update, the following versions are available:
```
2.4.9  2.5.7  2.6.5  2.7.0
```
In the future, Actions may support more Ruby versions, with an 'install-on-demand' model for any versions not in the toolcache.

If you must use 2.6.3, one alternative is [use-ruby-action](https://github.com/eregon/use-ruby-action)

**Comment by adbeelitamar** [comment] 2020-01-24 23:23
For now I must use 2.6.3, [use-ruby-action](https://github.com/eregon/use-ruby-action) did the work.

Thanks @MSP-Greg

**Comment by bryanmacfarlane** [comment] 2020-01-31 17:44
@adbeelitamar - see the main readme.  it's only reliable ti specify minor version bindings.  there's #49 to make better.

**Comment by bryanmacfarlane** [comment] 2020-01-31 22:11
For now, dupe of #44

**Closed by bryanmacfarlane** 2020-01-31 22:11 UTC
