### ISSUE TITLE
Ruby version removed without bumping major version

### ISSUE THREAD

**Issue by chrisseaton** [actions/setup-ruby#51] opened 2020-01-17 02:31 UTC
I pinned to `setup-ruby@v1` and Ruby `2.6.3`, but at some point `2.6.3` disappeared. Could you bump the major version of this action when you make a breaking change such as removing a Ruby version? Otherwise workflows just stop working even though I didn't change any configuration.

**Comment by garriguv** [comment] 2020-01-17 10:06
Hopefully not for too much longer :) https://github.com/actions/setup-ruby/pull/49

Also, `2.6.5` works if you're wondering.

**Comment by bryanmacfarlane** [comment] 2020-01-23 16:49
Bumping the major version would do no good.  It's the VM image that removed 2.6.3.

https://github.com/actions/virtual-environments/issues/281

**Comment by chrisseaton** [comment] 2020-01-23 16:53
Do you know if we can pin to a version of the VM image then? I want a build that will work both today *and* tomorrow.

**Comment by bryanmacfarlane** [comment] 2020-01-23 16:56
Nope.  It slides forward and what the VM script that builds that image happens to do is pull latest minor version.  I suggested in the issue ☝️ that it's additive

I updated the readme on this action in accordance to say effectively, you can only bind to minor until they change that.

And yes, #49 will allow it to pull JIT which means that your build won't break, it just might get 10 seconds slower when an older version rolls out of the cache.

**Comment by youhanaNaseim** [comment] 2020-01-23 17:00
@chrisseaton thanks for the feedback totally appreciate it. Apologize for the inconvenience this has caused. In general pinning to a minor version and not a patch version similar to what we have done here https://github.com/actions/setup-ruby/blob/master/.github/workflows/versions.yml should be enough to ensure your workflows continue to work. We do not remove minor versions from the VM images.

Your suggestion about pinning to a VM issues (after we version them somehow) is a great suggestion and is something on the team's backlog we do not have an ETA for that yet though. 

I hope this works for you and apologies for the inconveniences this has caused.

**Comment by chrisseaton** [comment] 2020-01-23 17:01
> In general pinning to a minor version ... We do not remove minor versions from the VM images.

Ah ok if that's an option I'll do that, thanks.

**Comment by bryanmacfarlane** [comment] 2020-01-23 17:16
@chrisseaton - I would be really interested in how important exact version binding is.  Specifically, older patch versions.

**Comment by chrisseaton** [comment] 2020-01-23 17:17
In my use-case some internals of MRI that I depend on change in patch versions.

**Comment by chrisseaton** [comment] 2020-01-23 17:17
...and hypothetically, a patch version could introduce a new bug that blocks you.

**Comment by MSP-Greg** [comment] 2020-01-23 18:01
Re changes from one teeny build to another, see a few possibilities at https://github.com/actions/virtual-environments/issues/281#issuecomment-575799275.

Also, teeny releases often have backports from ruby master, and, although not common, sometimes the backports aren't complete or correct.

**Comment by bryanmacfarlane** [comment] 2020-01-23 19:23
@chrisseaton - also note #49 which would be a solution to your issue.  Between https://github.com/actions/virtual-environments/issues/281 and #49, it covers what you need.  Is it OK to close this as a dupe of #49?

**Comment by bryanmacfarlane** [comment] 2020-01-23 22:36
Tracking in https://github.com/actions/virtual-environments/issues/281#issuecomment-575799275

@chrisseaton - if this didn't address your question, let us know and we can reactivate.

**Closed by bryanmacfarlane** 2020-01-23 22:36 UTC
